name: package-mnq-public-corpus-r1
on:
  pull_request:
    paths:
      - '.github/workflows/package-mnq-public-corpus-r1.yml'
permissions:
  contents: read
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - run: echo SHOULD_NOT_USE_MAIN_DIRECT=1
